### ISSUE TITLE
Travis matrix cross platform erase result (OSX override Linux results)

### ISSUE THREAD

**Issue by Milerius** [report-ci/scripts#4]
Hello it's seems that in case of travis matrix result from Linux are override by result of OSX:

Repository: https://github.com/Milerius/nephtys
Pull Request: https://github.com/Milerius/nephtys/pull/36
Proof: https://github.com/Milerius/nephtys/pull/36/checks?check_run_id=96177739

I'm expecting to check both result for **Linux** and **OSX**, for example actually I have four unit test on linux and only two on **OSX**

One of the solution is to use circle ci for osx and kick out osx from travis.yml, but honestly I don't want to do that I think !

Let me know !

**Comment by Milerius** [comment]
<img width="271" alt="Capture d’écran 2019-04-08 à 18 35 56" src="https://user-images.githubusercontent.com/21139416/55741287-332b1380-5a2d-11e9-9d0d-ce2b386f7031.png">

One of the solution can be to have travis-ci-linux and travis-ci-osx as report

**Comment by klemens-morgenstern** [comment]
This is the behaviour of github, it overwrites if you commit a check_run with the same name. It should be to `check_run`s since those are two test runs.

If you set the name manually, e.g. by passing `--name "Doctes [travis-ci $TRAVIS_OS_NAME]"` it should work.

Maybe I should add the `TRAVIS_OS_NAME` as a default.

**Comment by Milerius** [comment]
I think that's a good idea to add travis_os_name but as you wish
